# Типы данных Python

## Числа

In [ ]:
a = 5
b = 10.5

#сложение
print(a+b, ' сложение')

#умножение
print(a*b, ' умножение')

#возведение в степень
print(a**2, ' возведение в степень')

#деление
print(b/a, ' деление')

#деление (целая часть)
print(b//a, ' деление (целая часть)')

#деление (дробная часть)
print(b%a, ' деление (дробная часть)')

15.5  сложение
52.5  умножение
25  возведение в степень
2.1  деление
2.0  деление (целая часть)
0.5  деление (дробная часть)


## Строки

Строки (string) — это последовательности символов

In [ ]:
first_str = 'кот'
second_str = 'пес'

#конкатенация строк
some_string = first_str + 'о' + second_str
print('конкатенация:', some_string)

#длина строки
length = len(some_string)
print('длина строки:', length)

#первый символ строки
first_symbol = some_string[0]
print('первый символ строки:', first_symbol)

#последний символ строки
last_symbol = some_string[-1]
print('последний символ строки:', last_symbol)

#срез строки с первого по третий символ
cat_slice = some_string[0:3]
print('срез строки:', cat_slice)

#разделить строку по определенному символу
list_substring = some_string.split('о')
print(list_substring)

конкатенация: котопес
длина строки: 7
первый символ строки: к
последний символ строки: с
срез строки: кот
['к', 'т', 'пес']


## Списки

Список (list) — это упорядоченная коллекция объектов. Списки могут иметь сколько угодно уровней вложенности и хранить неограниченное количество объектов. Кроме того, в одном списке могут одновременно храниться объекты разных типов.

Над списками можно производить те же операции, что и над строками:

In [ ]:
some_list = ['к', 'о', 'т', 'о', 'п', 'е', 'с', 2]

#первый символ списка
first_list_symbol = some_list[0]
print('первый символ списка:', first_list_symbol)

первый символ списка: к


In [ ]:
#методы списков

#добавить новый элемент в конец списка
some_list.append('!')
print(some_list)

#удалить элемент с индексом 7
some_list.pop(7)
print(some_list)

#отсортировать элементы списка в порядке возрастания
some_list.sort()
print(some_list)

['к', 'о', 'т', 'о', 'п', 'е', 'с', 2, '!']
['к', 'о', 'т', 'о', 'п', 'е', 'с', '!']
['!', 'е', 'к', 'о', 'о', 'п', 'с', 'т']


## Также есть словари и кортеджи

#Массивы Numpy

Библиотека numpy позволяет работать быстро с многомерными массивами. В отличии от списков, массивы доллжны состоять из элементов только одного типа данных

In [ ]:
#импорт библиотеки
import numpy as np

##Cоздание массивов

In [ ]:
a = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)
print(a2)
print(a3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


##Создание специальных массивов

In [ ]:
#Возвращает равномерно распределенные значения в пределах заданного интервала (начало, конец, шаг).
a = np.arange(2, 10, 2)
print(a)

#массив из нулей с размерностью 2,3
#размерность указывается кортеджами
a_zeros = np.zeros((2, 3))
print(a_zeros)

#массив из единиц
a_ones = np.ones((2 ))
print(a_ones)

[2 4 6 8]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1.]


##Математические операции

In [ ]:
#Массивы из NumPy поддерживают все стандартные арифметические операции — например, сложение, деление, вычитание. Работает это поэлементно
a = np.array([1, 2, 3, 4])
print(a)
print(a + 3)
print(a * 2)
print(a / 2)

#если массивы одинакового размера
x = np.array([[1, 2], [3, 4]])
y = np.array([[2, 2], [2, 2]])
print(x+y)
print(x*y)

[1 2 3 4]
[4 5 6 7]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]


Больше возможностей с массивами в отдельном ноутбуке на диске

#DataFrame библиотеки pandas

In [ ]:
import pandas as pd

Библиотека pandas, которая применяется для обработки и анализа табличных данных. В этой библиотеке используется numpy для удобного хранения данных и вычислений.

В библиотеке pandas определены два класса объектов для работы с данными:

Series — одномерный массив, который может хранить значения любого типа данных; DataFrame — двумерный массив (таблица), в котором столбцами являются объекты класса Series.


##Series

В качестве данных объекта Series могут выступать: массив numpy, словарь, число. В аргумент index передаётся список меток осей. Метка может быть числом или строкой. Если индекс не передается, то меткам автоматически неазначается список [0, ..., len(data) - 1]

###Создание Series

In [ ]:
s = pd.Series(np.arange(5), index=["a", "b", "c", "d", "e"])
print(s)
print()

s = pd.Series(np.linspace(0, 1, 5))
print(s)
print()
#задать Series с помощью словаря
s = {"a": 10, "b": 20, "c": 30, "g": 40}
print(pd.Series(s))
print()

a    0
b    1
c    2
d    3
e    4
dtype: int64

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

a    10
b    20
c    30
g    40
dtype: int64



##DataFrame

DataFrame — это структуры, которые состоят из:

данных, организованных в двух измерениях — строках и столбцах;
и соответствующих этим строкам и столбцам меток.

###Создание и заполнение DataFrame

In [ ]:
#из словаря
students_marks_dict = {"student": ["Студент_1", "Студент_2", "Студент_3"],
                       "math": [5, 3, 4],
                       "physics": [4, 5, 5]}
students = pd.DataFrame(students_marks_dict)
print(students)

     student  math  physics
0  Студент_1     5        4
1  Студент_2     3        5
2  Студент_3     4        5


In [ ]:
#создание пустого DataFrame с последующим заполнением
empty_df = pd.DataFrame(columns = ['кот', 'возраст'])
empty_df.head()

Empty DataFrame
Columns: [кот, возраст]
Index: []

In [ ]:
#заполнение пустого DF списками
empty_df['кот'] = ['Вася', 'Пушистик', 'Рыжик']
empty_df.head()

кот возраст
0      Вася     NaN
1  Пушистик     NaN
2     Рыжик     NaN

In [ ]:
#важно, чтобы длина списка была одинакова с длиной DF
#empty_df['возраст'] = [1, 5]
#empty_df.head()

In [ ]:
empty_df['возраст'] = [1, 5, np.nan]
empty_df.head()

кот  возраст
0      Вася      1.0
1  Пушистик      5.0
2     Рыжик      NaN

###Доступ к элементам DF

In [ ]:
#вывод индексов и колонок
print(empty_df.index)
print(empty_df.columns)
#print(list(empty_df.columns))

RangeIndex(start=0, stop=3, step=1)
Index(['кот', 'возраст'], dtype='object')


In [ ]:
#доступ к строке
empty_df.loc[2]

кот        Рыжик
возраст      NaN
Name: 2, dtype: object

In [ ]:
#доступ к колонке
empty_df['кот']

0        Вася
1    Пушистик
2       Рыжик
Name: кот, dtype: object

In [ ]:
#доступ к одному элементу
empty_df.at[1, 'кот']

'Пушистик'

In [ ]:
#доступ по условиям
empty_df[empty_df['кот'] == 'Вася']

кот  возраст
0  Вася      1.0

Больше возможностей с DataFrame в отдельном ноутбуке на диске

# Условия в Python

In [ ]:
a = 1
b = 5
c = 6

In [ ]:
if a+b == c:
  print('Да')
else:
  print('Нет')

Да


In [ ]:
if a>b:
  print('a больше b')
elif a<b:
  print('a меньше b')
  print('это правильно')
else:
  print('a равно b')
print('код выполнен')

a меньше b
это правильно
код выполнен


In [ ]:
#альтернативное выполнение предыдущего кода
'''
if a>b:
  print('a больше b')
else:
  if a<b:
    print('a меньше b')
  else:
    print('a равно b')
'''

"\nif a>b:\n  print('a больше b')\nelse:\n  if a<b:\n    print('a меньше b')\n  else:\n    print('a равно b')\n"

# Циклы в Python

## while

While выполняется до тех пор, пока выполняется условие

In [ ]:
a = 0
while a <= 3:
  print(a)
  a += 1 #a = a + 1

0
1
2
3


## Операторы циклов

break - оператор досрочного завершения цикла

In [ ]:
a = 5
while a>0:
  print(a)
  if a**2 == 9:
    break
  a -= 1

5
4
3


In [ ]:
a = 5
while a>0:
  if a**2 == 9:
    break
  print(a)
  a -= 1

5
4


continue - оператор перехода к следующей итерации

In [ ]:
a = 5
while a>0:
  a -= 1
  if a**2 == 9:
    continue
  print(a)

4
2
1
0


## Цикл for

for - Повторяет действия определенное количество раз

In [ ]:
for i in 1,2,3:
  print(i + 1)

2
3
4


range - функция, возвращающая последовательность от start (вкл) до end (не вкл) с шагом step: (start, end, step)

In [ ]:
for i in range(1, 4, 1):
  print(i + 1)

2
3
4


In [ ]:
string_ex = 'кот'
for i in string_ex:
  print(i)

к
о
т


In [ ]:
list_ex = [[1, 2], [3, 4], [5, 6]]
for i in list_ex:
  print(i)

[1, 2]
[3, 4]
[5, 6]


# Домашнее задание

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
comment = ["Эта идея хорошо подходит для нашего проекта, молодцы!",
           "Хорошо, что вы подняли эту тему, она очень важна!",
           "Мне нравится, как вы изложили свои мысли, очень хорошо!",
           "К сожалению, ситуация здесь выглядит плохо, есть над чем поработать.",
           "Плохо, что такие мнения появляются, это не конструктивно.",
           "Увы, реализация идеи вышла плохо, нужно больше усилий!"]
np.random.seed(3)
like = np.random.randint(100, 600, (6, ))
repost = np.random.randint(10, 60, (6, ))
view = np.random.randint(500, 2500, (6, ))

1. Проанализировать список comment. Посчитать количество символов и слов в каждом комментарии.
2. Проанализировать список comment. Вывести на экран индекс комментария и напротив его тональность. (Если есть слово "хорошо", то тональность положительная, если есть слово "плохо", то тональность отрицательная)
3. Создать DataFrame из списков comment, like, repost, view с идентичными названиями колонок
4. Вывести на экран комментарий, у коготорого больше всего лайков.
5. Посчитать для каждого комментария оценку вовлеченности ((like + repost)/view)


In [ ]:
# 1. Анализ списка comment: подсчет количества символов и слов в каждом комментарии
print("1. Количество символов и слов в каждом комментарии:")
for idx, comm in enumerate(comment):
    n_chars = len(comm)
    n_words = len(comm.split())
    print(f"Комментарий {idx}: {n_chars} символов, {n_words} слов")
print("\n")

1. Количество символов и слов в каждом комментарии:
Комментарий 0: 53 символов, 8 слов
Комментарий 1: 49 символов, 9 слов
Комментарий 2: 55 символов, 9 слов
Комментарий 3: 68 символов, 10 слов
Комментарий 4: 57 символов, 8 слов
Комментарий 5: 54 символов, 8 слов




In [ ]:
# 2. Анализ списка comment: определение тональности комментария
print("2. Тональность комментариев:")
for idx, comm in enumerate(comment):
    # Приводим комментарий к нижнему регистру для корректного поиска
    comm_lower = comm.lower()
    if "хорошо" in comm_lower:
        tone = "положительная"
    elif "плохо" in comm_lower:
        tone = "отрицательная"
    else:
        tone = "не определена"
    print(f"Комментарий {idx}: {tone}")
print("\n")

2. Тональность комментариев:
Комментарий 0: положительная
Комментарий 1: положительная
Комментарий 2: положительная
Комментарий 3: отрицательная
Комментарий 4: отрицательная
Комментарий 5: отрицательная




In [ ]:
# 3. Создание DataFrame из списков comment, like, repost, view
df = pd.DataFrame({
    'comment': comment,
    'like': like,
    'repost': repost,
    'view': view
})
print("3. DataFrame из списков:")
print(df)
print("\n")

3. DataFrame из списков:
                                             comment  like  repost  view
0  Эта идея хорошо подходит для нашего проекта, м...   462      10  2174
1  Хорошо, что вы подняли эту тему, она очень важна!   252      31  1417
2  Мне нравится, как вы изложили свои мысли, очен...   349      29  1643
3  К сожалению, ситуация здесь выглядит плохо, ес...   231      20  1946
4  Плохо, что такие мнения появляются, это не кон...   540      53   980
5  Увы, реализация идеи вышла плохо, нужно больше...   556      51  2184




In [ ]:
# 4. Вывод комментария с наибольшим количеством лайков
max_like_index = df['like'].idxmax()
print("4. Комментарий с наибольшим количеством лайков:")
print(df.loc[max_like_index, 'comment'])
print("\n")

4. Комментарий с наибольшим количеством лайков:
Увы, реализация идеи вышла плохо, нужно больше усилий!




In [ ]:
# 5. Подсчет оценки вовлеченности для каждого комментария ((like + repost)/view)
df['engagement'] = (df['like'] + df['repost']) / df['view']
print("5. Оценка вовлеченности для каждого комментария:")
print(df[['comment', 'engagement']])

5. Оценка вовлеченности для каждого комментария:
                                             comment  engagement
0  Эта идея хорошо подходит для нашего проекта, м...    0.217111
1  Хорошо, что вы подняли эту тему, она очень важна!    0.199718
2  Мне нравится, как вы изложили свои мысли, очен...    0.230067
3  К сожалению, ситуация здесь выглядит плохо, ес...    0.128983
4  Плохо, что такие мнения появляются, это не кон...    0.605102
5  Увы, реализация идеи вышла плохо, нужно больше...    0.277930
